import axios from 'axios';


const API = axios.create({ baseURL: 'http://localhost:5000'});

//intercept HTTP requests, enables you to add listeners for various stages of making an HTTP request. front/backend authorization in every request.
API.interceptors.request.use((req) => {
   //sends token to backend and backend middleware can verify
   if(localStorage.getItem('profile')){
    //BearerToken : Bearer authentication (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens.
    //The bearer token is a cryptic string, usually generated by the server in response to a login request.
       req.headers.authorization =`Bearer ${JSON.parse(localStorage.getItem('profile')).token}`;
   }

   return req;
});

//sends to backend --> look server/index.js --app.use..

export const createNote = newNote => API.post('/notes', newNote);
export const fetchNotes = () => API.get('/notes');
export const deleteNote = (id) => API.delete(`/notes/${id}`);
export const updateNote = (id, editedNote) => API.patch(`/notes/${id}`, editedNote)
export const likePost = (id) => API.patch(`/notes/${id}/likePost`);


export const signIn = formData => API.post('/user/signin', formData);
export const signUp = formData => API.post('/user/signup', formData);